### PR TITLE
Small fixed from mass PR merge

### PR DESCRIPTION
**Pull request by DoctorDib**
Changes:
 - Fixed image upload
 - Removed debugger

### CODE REVIEW

**Comment by BenRGH** [comment]
You say you've removed a debugger but I don't see the change?

**Comment by DoctorDib** [comment]
That's strange, I removed this one:

ImageUploader/index.tsx:118
image

However I don't see it either. Perhaps I had a local copy maybe?

**Comment by BenRGH** [comment]
I think there's a chance debuggers are automatically ignored through git or eslint

**Comment by DoctorDib** [comment]
ESLint was the one who was complaining for me to remove it, so I did before committing

**Pull request merged**
